print([x * y for x in range(3) for y in range(3)])
print([x for x in range(10) if x % 2 == 0 if x > 2])
print({x: x ** 2 for x in range(5)})
print({x % 3 for x in range(10)})
print([[row[i] for row in [[1, 2], [3, 4]]] for i in range(2)])
print(list(x + 1 for x in range(3)))
print(sum(len(w) for w in ["a", "bb", "ccc"]))
matrix = [[1, 2, 3], [4, 5, 6]]
print([n for row in matrix for n in row])
print({k: v for k, v in zip("abc", [1, 2, 3])})
print([x if x > 0 else -x for x in [-1, 2, -3]])
