// Copyright 2026 Thomas Santerre and Moderately AI Inc.
//
// SPDX-License-Identifier: MIT OR Apache-2.0

/* Generated by NAPI-RS; this header is prepended from `dts-header.d.ts`. */
/* eslint-disable */

/**
 * A value that can cross the sandbox boundary, in either direction.
 *
 * Note two asymmetries, which are deliberate and documented rather than guessed:
 *
 * - A JS array always becomes a Python `list`, never a `tuple` — JavaScript has
 *   no tuple to distinguish. A Python tuple arrives here as a *frozen* array.
 * - A sandbox integer arrives as a `number` when it fits, and as a `bigint` when
 *   it exceeds `Number.MAX_SAFE_INTEGER`. Losing digits silently would be worse.
 *
 * Anything with no counterpart — a function, class, or instance defined *inside*
 * the sandbox — throws a `TypeError` naming the type rather than becoming `null`.
 */
export type SandboxValue =
  | null
  | undefined
  | boolean
  | number
  | bigint
  | string
  | Buffer
  | Uint8Array
  | Date
  | SandboxValue[]
  | ReadonlyArray<SandboxValue>
  | Set<SandboxValue>
  | Map<SandboxValue, SandboxValue>
  | { [key: string]: SandboxValue }

/**
 * A host tool: a plain function or an `async` one. Both work; the interpreter
 * awaits a returned promise.
 *
 * Arguments arrive as an object. Positional arguments from the script are named
 * `arg0`, `arg1`, ...; keyword arguments keep their names.
 *
 * Throwing is a normal outcome: the script sees a catchable `Exception`, and if
 * it does not catch it, the run fails with `kind: "tool"`.
 */
export type ToolFunction = (
  args: Record<string, SandboxValue>
) => SandboxValue | Promise<SandboxValue>

/**
 * A tool, optionally with settings.
 *
 * `parallelizable` lets the interpreter overlap this tool with other
 * parallelizable ones — safe only if it has no order-dependent side effects.
 */
export type ToolEntry =
  | ToolFunction
  | { func: ToolFunction; parallelizable?: boolean }
