print([x*2 for x in range(5)])
print([x for x in range(10) if x % 2 == 0])
print({x: x**2 for x in range(4)})
print({x % 3 for x in range(10)})
print([x+y for x in range(3) for y in range(3)])
print([[row[i] for row in [[1,2],[3,4]]] for i in range(2)])
print(list(x for x in range(5) if x > 2))
print([y for x in [[1,2],[3,4]] for y in x])
matrix = [[1, 2, 3], [4, 5, 6]]
print([[matrix[r][c] for r in range(2)] for c in range(3)])
print({k: v for k, v in zip("abc", [1, 2, 3])})
print(sum(x*x for x in range(5)))
n = 10
print([i for i in range(n) if all(i % j != 0 for j in range(2, i))])
print(sorted({x % 5 for x in range(20)}))
