from collections import deque, Counter, defaultdict, namedtuple, OrderedDict
d = deque([1, 2, 3], maxlen=3)
d.append(4); d.appendleft(0)
print(list(d))
d.rotate(1); print(list(d))
d.rotate(-2); print(list(d))
print(Counter("aabbbc"))
print(Counter("aabbbc").most_common(2))
c = Counter(a=3, b=1); c.update(a=1, c=5); print(dict(c))
print(Counter([1,2,2,3]) + Counter([2,3,3]))
print(Counter([1,1,2]) - Counter([1,3]))
dd = defaultdict(list); dd["x"].append(1); dd["x"].append(2); print(dict(dd))
dd2 = defaultdict(int); dd2["a"] += 5; print(dict(dd2))
Point = namedtuple("Point", ["x", "y"])
p = Point(1, 2); print(p, p.x, p.y, p._asdict(), p._replace(x=9))
print(p[0], tuple(p), Point._fields)
od = OrderedDict([("a", 1), ("b", 2)]); od.move_to_end("a"); print(list(od))
