print(list(map(lambda x: x*2, [1, 2, 3])))
print(list(filter(lambda x: x > 2, [1, 2, 3, 4])))
print(list(zip([1, 2, 3], "abc")))
print(list(enumerate("abc", start=1)))
print(any([False, True]), all([True, True]), any([]), all([]))
print(sorted([3, 1, 2], key=lambda x: -x))
print(list(reversed([1, 2, 3])))
print(len("hello"), len([1, 2]), len({1: 2}))
print(max("abc"), min([3, 1, 2]), sum(range(5)))
print(abs(-7), round(3.7), pow(2, 8))
print(chr(65), ord("Z"), hex(255), bin(5), oct(8))
print(repr("a\nb"), str(42), ascii("café"))
print(isinstance(5, int), issubclass(bool, int))
print(list(map(pow, [2, 3], [3, 2])))
print(tuple(map(int, ["1", "2", "3"])))
print(dict(zip("abc", range(3))))
print(frozenset([3, 1, 2, 1]))
print(sorted("dcba", reverse=True))
print(list(zip(*[[1, 2], [3, 4]])))
print(next(iter([10, 20])), next(iter({}), "empty"))
