import re
print(re.findall(r"\d+", "a1b22c333"))
print(re.sub(r"\d", "#", "a1b2c3"))
print(re.match(r"(\w+)@(\w+)", "user@host").groups())
print(re.search(r"\d+", "abc123def").group())
print(re.split(r"[,;]", "a,b;c,d"))
print(bool(re.fullmatch(r"\d{3}", "123")))
print(re.sub(r"(\w+) (\w+)", r"\2 \1", "hello world"))
print(re.findall(r"(\w)(\d)", "a1b2c3"))
print([m.group() for m in re.finditer(r"\d+", "1 22 333")])
print(re.sub(r"\s+", " ", "a   b    c"))
p = re.compile(r"^\d{4}-\d{2}-\d{2}$")
print(bool(p.match("2024-01-15")))
print(re.match(r"(?P<year>\d{4})", "2024").group("year"))
print(re.subn(r"a", "X", "banana"))
print(re.escape("a.b*c"))
print(re.findall(r"[aeiou]", "hello world"))
print(re.sub(r"(\d)", lambda m: str(int(m.group())*2), "123"))
print(re.split(r"(\d)", "a1b2"))
print(re.findall(r"\bword\b", "a word here"))
