print(repr([1, "a", None, True, 3.14]))
print(repr({"key": [1, 2], "n": None}))
print(repr((1,)))
print(repr(()))
print(repr({1, 2, 3}))
print(repr(frozenset()))
print(repr(""))
print(repr("with 'quotes' and \"both\""))
print(repr('has "double"'))
print(repr("tab\there"))
print(repr(b"bytes\x00\xff"))
print(repr([[], {}, set(), ()]))
print(str([1, 2]), str({1: 2}))
print(repr(-0.0), repr(1e100), repr(1e-100))
print(repr(float("inf")), repr(float("-inf")), repr(float("nan")))
print(repr(1000000000000000000000))
print(repr("\n\t\r\\"))
print(repr(chr(0)), repr(chr(127)), repr(chr(128)))
print(repr("emoji"), repr("\x1f"))
l = [1]; l.append(l); print(repr(l))
d = {}; d["self"] = d; print(repr(d))
