print("café".encode("utf-8"))
print("café".encode("utf-8").decode("utf-8"))
print("hello".encode("ascii"))
print(b"\xe2\x82\xac".decode("utf-8"))
print("abc".encode("utf-16"))
print(len("café"), len("café".encode("utf-8")))
print("naïve".upper(), "STRASSE".lower())
print("Hello World".encode("utf-8").hex())
print(bytes.fromhex("48656c6c6f").decode())
print("test".encode().decode())
try:
    "café".encode("ascii")
except UnicodeEncodeError as e:
    print("UEE")
print("café".encode("ascii", "ignore"))
print("café".encode("ascii", "replace"))
print("café".encode("ascii", "xmlcharrefreplace"))
print("\U0001F600".encode("utf-8"))
print("abc\ndef".encode())
print(ord("€"), hex(ord("€")))
print("100°".encode("latin-1"))
