print(type(42) is int)
print(type("x") is str)
print(type([]) is list)
print(type({}) is dict)
print(type(()) is tuple)
print(type(3.14) is float)
print(type(True) is bool)
print(type(None) is type(None))
print(isinstance(42, (int, float)))
print(isinstance(True, int))
print(isinstance("x", str))
print(int == int)
print(str != int)
print([int, str, float][0] is int)
print(callable(int), callable(42))
print(type(type(42)))
print(int.__name__, str.__name__, list.__name__)
print(bool.__name__)
