print(sum([1, 2, 3], 10))
print(min([3, 1, 2], key=lambda x: -x))
print(max("abc", "ab", key=len))
print(list(enumerate("ab", start=1)))
print(list(zip([1, 2], [3, 4, 5])))
print(list(filter(None, [0, 1, 2, 0, 3])))
print(all([1, 2, 3]), any([0, 0]))
print(list(reversed(range(3))))
print(list(map(lambda x, y: x + y, [1, 2], [10, 20])))
print(sorted([3, 1, 2], reverse=True))
