print(list(zip([1, 2, 3], [4, 5, 6], strict=True)))
print(sorted([("b", 2), ("a", 1)], key=lambda x: x[0]))
print(list(map(str, [1, 2, 3])))
print(list(filter(lambda x: x > 2, [1, 2, 3, 4])))
print(sum([], []))
print(any(x % 2 == 0 for x in [1, 3, 5, 6]))
print(next(iter([10, 20, 30])))
print(list(enumerate(["a", "b"], 1)))
print(min([], default=None))
print(sorted("dcba"))
print(list(reversed("abc")))
print(bool([]), bool([0]))
print(tuple(map(lambda x: x**2, range(4))))
print(dict(enumerate("ab")))
print(frozenset([1, 2, 3]).union([4, 5]))
print(list(zip(*[[1, 2], [3, 4]])))
