print(min([3,1,2], key=lambda x: -x))
print(max([], default="none"))
print(list(enumerate("ab", start=5)))
print(list(zip([1,2],[3,4,5])))
print(list(map(lambda a,b: a+b, [1,2],[10,20])))
print(list(filter(None, [0,1,2,0,3])))
print(all([]), any([]))
print(divmod(7, 3))
print(divmod(-7, 3))
print(divmod(7.5, 2))
print(sorted([3,1,2], reverse=True))
print(sum([1,2,3], 10))
print(list(reversed(range(3))))
print(abs(-3+4j))
