print(chr(65), ord("A"))
print(hex(255), oct(8), bin(5))
print(abs(-3.5), abs(complex(3, 4)))
print(divmod(17, 5))
print(pow(2, 10), pow(2, 10, 1000))
print(round(3.14159, 2))
print(sorted([3, 1, 2], reverse=True))
print(list(filter(None, [0, 1, "", "a", None, [], [1]])))
print(sum(range(5)))
print(max("hello"), min("hello"))
print(all([True, 1, "a"]), any([0, "", None]))
print(len(range(0, 10, 2)))
print(list(map(lambda x, y: x + y, [1, 2], [10, 20])))
print(repr("with 'quotes'"))
print(ascii("café"))
print(format(255, "b"))
print(bytes(3))
print(bytearray([65, 66, 67]))
print(list(zip("abc", range(3))))
