b = b"hello world"
print(b.upper())
print(b.split())
print(b.replace(b"o", b"0"))
print(b[::-1])
print(bytes([72, 105]))
print(b"abc".hex())
print(bytes.fromhex("4869"))
print(b"a,b,c".split(b","))
print(len(b"hello"))
print(b"HELLO".lower().decode())
print(b"  trim  ".strip())
print(b"x" * 3)
print(b"abc" + b"def")
ba = bytearray(b"test")
ba[0] = 84
print(ba)
ba.append(33)
print(bytes(ba))
