ba = bytearray(b"hello")
ba[0] = ord("H")
print(ba)
ba.extend(b" world")
print(ba)
print(ba.upper())
print(ba.split())
print(ba.replace(b"o", b"0"))
print(bytes(ba))
print(ba.decode())
print(ba.count(b"l"))
print(ba.find(b"world"))
ba2 = bytearray(range(5))
print(list(ba2))
ba2.reverse()
print(list(ba2))
print(bytearray(b"ABC").hex())
print(len(bytearray(b"test")))
print(bytearray(b"abc") + bytearray(b"def"))
