b = b"Hello, World!"
print(b.lower())
print(b.upper())
print(b.split(b", "))
print(b.replace(b"o", b"0"))
print(b.startswith(b"Hello"))
print(b.endswith(b"!"))
print(b.find(b"World"))
print(b.count(b"l"))
print(b.strip(b"!"))
print(b[:5])
print(b[::-1])
print(len(b))
print(b.index(b"World"))
print(b.rfind(b"o"))
print(b.center(20, b"*"))
print(b.ljust(20, b"."))
print(b.partition(b", "))
print(b.hex())
print(bytes.fromhex("48656c6c6f"))
print(b.translate(bytes.maketrans(b"lo", b"LO")))
