b = b"hello world"
print(b.upper())
print(b.split())
print(b.replace(b"o", b"0"))
print(b.startswith(b"hello"))
print(b.find(b"world"))
print(b[::-1])
print(b[:5])
print(len(b))
print(b.count(b"o"))
ba = bytearray(b"abc")
ba[0] = 65
print(ba)
ba.append(33)
print(ba)
print(bytes([72, 105]))
print(b"a" + b"b")
print(b"ab" * 3)
print(list(b"abc"))
