z = 3 + 4j
print(f"{z}")
print(f"{z:.2f}")
print(str(1j))
print(str(-1j))
print(str(complex(0, 0)))
print(str(complex(1, 0)))
print(repr(2 + 3j))
print(abs(3 + 4j))
print((1 + 2j).conjugate())
print((2 + 3j) + (1 - 1j))
print((1 + 1j) * (1 - 1j))
print(complex(5))
print(complex("2+3j"))
print((3 + 4j).real, (3 + 4j).imag)
print(1j ** 2)
print((1 + 0j) == 1)
