from collections import Counter
a = Counter(["x", "x", "y"])
b = Counter(["x", "y", "y", "z"])
print(a + b)
print(a - b)
print(a & b)
print(a | b)
c = Counter("aabbc")
c.update("abc")
print(dict(c))
c.subtract("aa")
print(dict(c))
print(Counter([1, 1, 2]).most_common())
print(sorted((+Counter({"a": 1, "b": -1})).items()))
print(list((Counter({"a": 2, "b": 1})).elements()))
