from decimal import Decimal
print(Decimal('-0.0'))
print(Decimal('-0'))
print(Decimal('-0.00'))
print(str(Decimal('-0.0')))
print(Decimal('-0.0') == Decimal('0.0'))
print(Decimal('-0.0') == 0)
print(-Decimal('0'))
print(-Decimal('0.0'))
print(-Decimal('-0.0'))
print(Decimal('0.0'))
print(Decimal('-1.5'))
print(Decimal('-0.0') + Decimal('0'))
print(abs(Decimal('-0.0')))
