from collections import deque
d = deque([1, 2, 3], maxlen=3)
d.append(4)
print(list(d))
d.appendleft(0)
print(list(d))
print(d.maxlen)
d2 = deque(maxlen=2)
d2.extend([1, 2, 3, 4])
print(list(d2))
d3 = deque([1, 2, 3])
d3.rotate(-1)
print(list(d3))
d3.extendleft([0, -1])
print(list(d3))
print(len(deque([1, 2, 3])))
