from fractions import Fraction
print(Fraction(1, 2) + Fraction(1, 3))
print(Fraction(3, 4) * Fraction(2, 3))
print(Fraction(1, 2) / Fraction(1, 4))
print(Fraction(6, 8))
print(Fraction(0.5))
print(Fraction("3/7"))
print(Fraction(1, 2) < Fraction(2, 3))
print(float(Fraction(1, 3)))
print(Fraction(10, 4).numerator, Fraction(10, 4).denominator)
print(Fraction(1, 2) + 1)
print(Fraction(3, 6) == Fraction(1, 2))
print(Fraction(7, 2).__floor__())
print(Fraction(7, 2).__ceil__())
print(Fraction(-1, 3))
print(Fraction(2, 3) ** 2)
