print((255).to_bytes(2, "big").hex())
print(int.from_bytes(b"\x01\x02", "big"))
print((10).bit_length())
print((-256).bit_length())
print((0b1111).bit_count())
print((100).__index__())
print((5).__int__())
print((7).__float__())
print((10).__bool__())
print((42).conjugate())
print((5).numerator, (5).denominator)
print((10).real, (10).imag)
print(int.from_bytes(b"\xff", "big", signed=True))
print((256).to_bytes(2, "little"))
print((-1).to_bytes(1, "big", signed=True))
print((1000000).__repr__())
print((255).bit_length())
print(bool.from_bytes(b"\x01", "big"))
