print((255).bit_length())
print((0).bit_length())
print((1024).bit_length())
print((10).to_bytes(2, "big"))
print(int.from_bytes(b"\x00\xff", "big"))
print((255).bit_count())
print((-5).bit_length())
print((7).__index__())
print((10) .as_integer_ratio())
print((100).to_bytes(4, "little").hex())
