import itertools as it
print(list(it.product([1, 2], ["a", "b"])))
print(list(it.product(range(2), repeat=3)))
print(list(it.permutations([1, 2, 3])), list(it.permutations([1, 2, 3], 2)))
print(list(it.combinations([1, 2, 3, 4], 2)))
print(list(it.combinations_with_replacement([1, 2, 3], 2)))
print(list(it.accumulate([1, 2, 3, 4])), list(it.accumulate([1, 2, 3, 4], lambda a, b: a * b)))
print([list(g) for k, g in it.groupby([1, 1, 2, 3, 3, 3, 1])])
print([(k, list(g)) for k, g in it.groupby("aabbbc")])
print(list(it.chain([1, 2], [3, 4], [5])))
print(list(it.zip_longest([1, 2, 3], ["a", "b"], fillvalue="?")))
print(list(it.islice(it.count(10), 5)), list(it.islice(range(20), 2, 10, 3)))
print(list(it.takewhile(lambda x: x < 5, [1, 3, 6, 2])), list(it.dropwhile(lambda x: x < 5, [1, 3, 6, 2])))
print(list(it.starmap(pow, [(2, 3), (2, 10)])))
print(list(it.compress("ABCDEF", [1, 0, 1, 0, 1, 1])))
print(list(it.pairwise([1, 2, 3, 4])))
