lst = [3, 1, 2]
lst.sort()
print(lst)
lst.insert(0, 99)
print(lst)
print(lst.index(2))
print([1, 1, 2, 1].count(1))
lst.extend([7, 8])
print(lst)
lst.remove(99)
print(lst)
print(lst.pop())
print(lst.pop(0))
lst.reverse()
print(lst)
a = [1, 2, 3]
b = a.copy()
b.append(4)
print(a, b)
print([1, 2] + [3, 4])
print([0] * 3)
