import math
print(math.sqrt(16))
print(math.floor(3.7), math.ceil(3.2))
print(math.gcd(48, 36))
print(math.factorial(5))
print(round(math.pi, 4))
print(math.log(math.e))
print(math.log2(8), math.log10(1000))
print(math.sin(0), math.cos(0))
print(math.degrees(math.pi), math.radians(180))
print(math.hypot(3, 4))
print(math.gcd(12, 8, 4))
print(math.comb(5, 2), math.perm(5, 2))
print(math.trunc(-3.7))
print(math.copysign(3, -1))
print(math.fmod(7, 3))
print(math.isnan(float("nan")), math.isinf(float("inf")))
