import math
print(math.prod([1, 2, 3, 4]))
print(math.prod([], start=10))
print(math.dist([0, 0], [3, 4]))
print(math.remainder(10, 3))
print(math.ldexp(1.5, 3))
print(math.frexp(8.0))
print(math.modf(3.75))
print(math.log(100, 10))
print(math.expm1(0))
print(math.log1p(0))
print(math.atan2(1, 1))
print(math.tau)
print(round(math.gamma(5), 1))
print(math.isqrt(17))
print(math.floor(-2.5), math.ceil(-2.5))
print(math.copysign(-3, 1))
