from collections import namedtuple
Point = namedtuple("Point", ["x", "y"])
p = Point(1, 2)
print(p.x, p.y)
print(p[0], p[1])
print(p._asdict())
q = p._replace(x=10)
print(q)
print(Point._fields)
p2 = Point._make([3, 4])
print(p2)
print(list(p))
a, b = p
print(a, b)
print(p == Point(1, 2))
Color = namedtuple("Color", "r g b")
c = Color(255, 128, 0)
print(c.r, c.g, c.b)
print(len(p))
