import operator
print(operator.add(3, 4))
print(operator.mul(3, 4))
print(operator.sub(10, 3))
print(operator.truediv(10, 4))
print(operator.floordiv(10, 3))
print(operator.mod(10, 3))
print(operator.pow(2, 5))
print(operator.neg(5))
print(operator.lt(1, 2), operator.eq(2, 2))
print(operator.itemgetter(1)([10, 20, 30]))
print(operator.itemgetter(0, 2)([10, 20, 30]))
print(operator.attrgetter("real")(3+4j))
print(sorted([("b", 2), ("a", 1)], key=operator.itemgetter(0)))
print(operator.contains([1, 2, 3], 2))
print(operator.concat([1, 2], [3, 4]))
from functools import reduce
print(reduce(operator.add, [1, 2, 3, 4]))
print(reduce(operator.mul, [1, 2, 3, 4]))
print(operator.and_(6, 3), operator.or_(4, 1), operator.xor(5, 3))
