def te(f):
    try:
        f()
    except TypeError as e:
        return str(e)
print(te(lambda: 1 + "x"))
print(te(lambda: "x" - "y"))
print(te(lambda: [1] + (2,)))
print(te(lambda: {1} + {2}))
print(te(lambda: 1 < "x"))
print(te(lambda: [1, 2] < 3))
print(te(lambda: None + 1))
print(te(lambda: len(5)))
print(te(lambda: "a" * "b"))
print(te(lambda: {} + {}))
print(te(lambda: (1, 2) * "x"))
print(te(lambda: 5[0]))
print(te(lambda: 5(1)))
print(te(lambda: iter(5)))
print(te(lambda: "abc" + 5))
print(te(lambda: 3.0 + "x"))
print(te(lambda: sorted(5)))
print(te(lambda: 1 | "x"))
print(te(lambda: [] < ()))
print(te(lambda: 1 & 2.0))
print(te(lambda: "abc".join([1, 2])))
print(te(lambda: hash([1, 2])))
print(te(lambda: -"x"))
print(te(lambda: ~3.5))
print(te(lambda: 5 in 10))
print(te(lambda: "x" in 5))
