print("a b c d".split())
print("a,b,c".split(","))
print("a  b   c".split())
print("x".join(["1", "2", "3"]))
print("".join(["a", "b", "c"]))
print("one\ntwo\nthree".splitlines())
print("a-b-c-d".split("-", 2))
print("a-b-c-d".rsplit("-", 2))
print("  hello  ".split())
print("".split())
print("".split(","))
print("abc".split(""))  if False else print("skipped")
print(",".join([]))
print("|".join("abc"))
print("\n".join(["line1", "line2"]))
print(list("hello"))
print("Hello World Foo".split(" "))
print("trailing,".split(","))
print(",leading".split(","))
print("a,,b".split(","))
print("=".join(str(i) for i in range(4)))
