print(bool(0), bool(1), bool(""), bool("x"), bool([]), bool([0]))
print(bool(0.0), bool(0.1), bool(None), bool({}))
print(int(3.9), int(-3.9), int("42"), int(True))
print(float("3.14"), float("inf"), float("-inf"), float(2))
print(str(42), str(3.14), str([1,2]), str(None), str(True))
print(list("abc"), list((1,2)), list(range(3)), list({1,2,3}))
print(tuple([1,2,3]), tuple("ab"))
print(set([1,1,2,3]), sorted(set("hello")))
print(dict([("a",1),("b",2)]))
print(complex(3), complex("2j"))
print(bytes("hi", "utf-8"), bytearray([65,66]))
print(int("  42  "), float("  1.5  "))
print(bool(float("nan")))
print(list(enumerate("ab")))
print(str(b"bytes"))
print(int(3.0), int(2.5))
