print((255).bit_length())
print((0).bit_length())
print((10).__index__())
print((-5).__abs__())
print((7).__float__())
print((255).to_bytes(2, "big"))
print(int.from_bytes(b"\x01\x00", "big"))
print((10).numerator, (10).denominator)
print((5).real, (5).imag)
print((42).conjugate())
print((17).bit_count())
print(float.is_integer(3.0), float.is_integer(3.5))
print((2.5).as_integer_ratio())
print((3.14).hex())
print(float.fromhex("0x1.8p0"))
