import operator
print(operator.add(3, 4))
print(operator.mul(5, 6))
print(operator.sub(10, 3))
print(operator.truediv(15, 4))
print(operator.floordiv(15, 4))
print(operator.mod(17, 5))
print(operator.pow(2, 8))
print(operator.neg(5))
print(operator.abs(-7))
print(operator.eq(3, 3), operator.ne(3, 4))
print(operator.lt(2, 5), operator.gt(5, 2))
print(operator.and_(12, 10), operator.or_(12, 10), operator.xor(12, 10))
print(operator.contains([1,2,3], 2))
print(operator.getitem([10,20,30], 1))
print(operator.itemgetter(1)([10,20,30]))
print(operator.itemgetter(0, 2)([10,20,30]))
print(list(map(operator.itemgetter("name"), [{"name":"a"}, {"name":"b"}])))
print(operator.attrgetter("real")(5))
print(sorted([(1,"b"),(1,"a")], key=operator.itemgetter(1)))
print(operator.concat([1,2], [3,4]))
print(operator.not_(False), operator.truth(1))
