
print(sorted([1,2,3], key=lambda x: x, reverse=True))
print("".join(map(str, range(5))))
print(list(zip(*[[1,2,3],[4,5,6],[7,8,9]])))
print({**{"a":1}, **{"b":2}})
print([x for x in range(20) if x%2==0][::2])
print(dict(zip("abc", "xyz")))
print("hello world".title().swapcase())
print(max([], default=0), min([], default=-1))
print(sum([[1],[2]], []))
print(list(filter(lambda x: x>0, [-1, 0, 1, 2])))
print(any(x>10 for x in []), all(x>0 for x in []))
print([*"ab", *"cd"])
print({*[1,2], *[2,3]})
print((lambda *a, **k: (a, sorted(k.items())))(1, 2, x=3, y=4))
print(list(enumerate(reversed(["a","b","c"]))))
print("-".join(str(i) for i in range(5)))
print(sorted("dcba", reverse=True))
print(list(map(lambda x, y: x*y, [1,2,3], [4,5,6])))
print(round(3.14159, 3), round(2.5), round(-2.5))
print(abs(-3.14), abs(3+4j), pow(2, 10))
print(f"{123456789:,}", f"{0.5:.1%}", f"{255:#x}")
