import string
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.digits)
print(string.punctuation)
print(string.ascii_letters)
print(string.hexdigits)
print(string.octdigits)
print(string.whitespace == " \t\n\r\x0b\x0c")
print(string.capwords("hello world foo"))
print(string.capwords("a-b-c", "-"))
t = string.Template("$name is $age")
print(t.substitute(name="Bob", age=30))
print(t.safe_substitute(name="Alice"))
print(string.Template("${x}y").substitute(x=1))
