b = b"Hello World"
print(b.upper())
print(b.split(b" "))
print(b.replace(b"o", b"0"))
print(b.hex())
print(bytes.fromhex("48656c6c6f"))
print(b[::2])
print(b.startswith(b"Hello"))
print(b.find(b"World"))
print(b.count(b"o"))
ba = bytearray(b"abc")
ba.append(100)
print(ba)
ba.extend(b"ef")
print(bytes(ba))
print(list(b"ABC"))
print(b"a,b,c".split(b","))
print(int.from_bytes(b"\x01\x00", "big"))
print((1024).to_bytes(2, "little"))
print(b"  trim  ".strip())
