import math
print(math.factorial(5))
print(math.comb(5, 2), math.perm(5, 2))
print(round(math.log2(8)), round(math.log10(1000)))
print(math.isclose(0.1+0.2, 0.3))
print(math.dist([0,0], [3,4]))
print(math.hypot(3, 4))
print(math.copysign(3, -1))
print(math.fmod(7, 3))
print(round(math.degrees(math.pi), 1))
print(round(math.radians(180), 4))
print(math.gcd(48, 36, 24))
print(math.prod([1,2,3,4]))
print(math.isqrt(17))
print(math.trunc(-3.7))
print(round(math.atan2(1, 1), 4))
print(math.floor(math.e), math.ceil(math.e))
