result = [1, 2, 3, 4, 5]
print(list(filter(lambda x: x > 2, map(lambda x: x * 2, result))))
print("  Hello World  ".strip().lower().replace(" ", "_"))
print(sorted([3, 1, 2])[::-1])
print("a,b,c".split(",")[1].upper())
print([x for x in range(10)][2:5])
print({"a": 1, "b": 2}.get("a", 0) + 1)
data = [{"v": 3}, {"v": 1}, {"v": 2}]
print(sorted(data, key=lambda d: d["v"])[0]["v"])
print(list(range(10))[::2][1:])
print("hello".upper().lower().capitalize())
print(str(42).zfill(5).lstrip("0"))
print(max([1,2,3], key=lambda x: -x))
print(" ".join(reversed("a b c".split())))
print(len([x for x in "hello" if x in "aeiou"]))
print(list(map(str.upper, "abc")))
print(dict(sorted({"b": 2, "a": 1}.items()))["a"])
print("".join(sorted("dcba")))
print([[j for j in range(i)] for i in range(4)])
