print("Hello {}, you are {}".format("Bob", 25))
print("{1} {0}".format("world", "hello"))
print("{x} {y}".format(x=1, y=2))
print("%s is %d" % ("age", 30))
print("%(name)s: %(val).2f" % {"name": "pi", "val": 3.14159})
print("{:>10}".format("right"))
print("{:*^20}".format("center"))
print("{:.3}".format("truncated"))
print("value={0!r}".format("quoted"))
print("{:%}".format(0.5))
print("π = {:.5f}".format(3.14159265))
print("{0}{0}{0}".format("ab"))
s = "The quick brown fox"
print(s.split()[::-1])
print(" ".join(w.capitalize() for w in s.split()))
print(s.replace("quick", "slow"))
print(len(s), s.upper().count("O"))
print("a-b-c-d".split("-", 2))
print("  multi  word  string  ".split())
print("Hello\tWorld\n".strip())
