b = bytearray(b"hello")
b[0] = 72
print(bytes(b))
b.insert(0, 33)
print(bytes(b))
b.reverse()
print(bytes(b))
print(bytes([1,2,3]).rjust(5, b"\x00"))
print(b"abc".zfill(6))
print(b"Hello World".title())
print(b"HELLO".capitalize())
print(b"a1b2".isalnum(), b"abc".isalpha())
print(b"  spaces  ".strip())
print(b"line1\nline2".splitlines())
print(b"a-b-c".replace(b"-", b"+"))
print(bytes(range(65, 70)))
print(b"\x00\x01\x02".hex(":"))
print(bytes.fromhex("ff00ff"))
print(b"ABCDEF"[1:4])
print(len(b"hello"), b"hello"[0])
print(b"aaa".count(b"a"))
print(memoryview(b"abc")[0])
print(b"test".ljust(8, b"."))
print(b",".join([b"a", b"b", b"c"]))
