print(bool.__int__(True))
print(int.__int__(5))
print(int.__add__(10, 5))
print(int.__float__(7))
print(float.__int__(3.9))
print(int.__index__(42))
print(str.__len__("hello"))
print(str.__add__("a", "b"))
print(list.__len__([1,2,3]))
print(int.__mul__(3, 4))
print(bool.__index__(True))
print(int.__mod__(17, 5))
print(str.__contains__("hello", "ell"))
print(int.__abs__(-5))
print(float.__float__(2.5))
