print(True | False)
print(True & True)
print(True ^ True)
print(False | False)
print(type(True | False).__name__)
print(type(True & False).__name__)
print(type(True ^ False).__name__)
print(True | 2)
print(type(True | 2).__name__)
print(True & 0)
print([True | False, True & True])
