print("Hello World".casefold())
print("  spaced  ".strip())
print("a,b,,c".split(","))
print("a-b-c".rsplit("-", 1))
print("Hello".center(11, "*"))
print("abcabc".replace("a", "X", 1))
print("%.3f" % 3.14159)
print("{:>10}".format("hi"))
print("{name}={val}".format(name="x", val=5))
print("café".encode("utf-8"))
print("Hello".removeprefix("He"))
print("Hello".removesuffix("lo"))
print("Test123".isidentifier())
print("  \t\n ".isspace())
print("ABC".swapcase())
