print("café".encode("utf-8").decode("utf-8"))
print("Hello".maketrans("lo", "LO") is not None)
print("hello".translate(str.maketrans("lo", "LO")))
print("a b c".split(maxsplit=1))
print("a,b,c,d".rsplit(",", 2))
print("Hello World".rindex("o"))
print("aaa".rfind("a"))
print("Hello".expandtabs())
print("\t".expandtabs(4))
print("Hello World Foo".rsplit(None, 1))
print("mixedCASE".swapcase())
print("hello".center(11))
print("  strip  ".strip())
print("prefix_text".removeprefix("prefix_"))
print("ABCabc".isupper(), "ABC".isupper())
print("café".isalpha())
print("test123".isalnum())
print("  ".isspace())
print("Hello".isidentifier(), "123".isidentifier())
print("naïve".upper())
print("STRASSE".lower())
print("hello world".count("o", 0, 5))
