import itertools
print(list(itertools.permutations([1,2,3], 2)))
print(list(itertools.combinations([1,2,3,4], 2)))
print(list(itertools.combinations_with_replacement([1,2], 2)))
print(list(itertools.product([1,2], ["a","b"])))
print(list(itertools.product([0,1], repeat=3)))
print(list(itertools.chain([1,2], [3,4], [5])))
print(list(itertools.chain.from_iterable([[1,2],[3,4]])))
print(list(itertools.islice(range(100), 5, 15, 2)))
print([list(g) for k, g in itertools.groupby([1,1,2,3,3,3])])
print(list(itertools.filterfalse(lambda x: x%2, range(10))))
print(list(zip(*itertools.batched("ABCDEF", 2))))
print(list(itertools.accumulate([1,2,3], lambda a,b: a*b)))
print(list(itertools.repeat("x", 3)))
print(list(itertools.count(5, 2))[:3] if False else list(itertools.islice(itertools.count(5,2), 3)))
