
print("Hello, World!".split(", "))
print("  multi\n  line\n  text".strip())
print("abcABC123".isalnum())
print("Hello".encode("utf-16").decode("utf-16"))
print("%s=%r" % ("key", "value"))
print("{:>{}}".format("x", 5))
print("café".casefold())
print("ABCDEF".lower().upper())
print("aXbXc".replace("X", "-"))
print("hello world foo".split(None, 1))
print(",".join([]))
print("test".ljust(10, ".").rstrip("."))
print("Hello World".count("o"))
print("  x  y  ".split())
print("line1\r\nline2".splitlines())
print("abcdef"[1:5:2])
print("Hello".startswith("He"), "Hello".endswith("lo"))
print(chr(0x41) + chr(0x42))
print(ord("Z"))
print("hello".translate(str.maketrans("el", "ip")))
