import cmath
c = 2 + 3j
print(c + 1)
print(c - 1j)
print(c.conjugate())
print(abs(3 + 4j))
print(cmath.phase(1j))
print(cmath.polar(1 + 1j))
print(cmath.rect(1, 0))
print((1j) ** 2)
print(complex(1, 2) == complex(1, 2))
print((2 + 3j).real, (2 + 3j).imag)
print(cmath.sqrt(-1))
print(cmath.exp(0))
print(round(abs(cmath.exp(1j * cmath.pi) + 1), 10))
print((1 + 2j) + (3 + 4j))
print((6 + 8j) / 2)
print(complex("3+4j"))
print(hash(complex(1, 0)) == hash(1))
