print(list(zip([1,2,3], "abc")))
print(list(reversed(range(5))))
print(list(enumerate("xyz")))
it = iter([1,2,3])
print(next(it), next(it))
print(list(it))
print(sorted(set([3,1,2,1,3])))
print(list(map(str, range(3))))
print(dict(zip("abc", [1,2,3])))
print(tuple(range(0, 10, 2)))
print(sum(range(101)))
gen = (x**2 for x in range(4))
print(list(gen))
print([*range(3), *range(3)])
a, *b, c = [1,2,3,4,5]
print(a, b, c)
first, *rest = "hello"
print(first, rest)
print(list(filter(lambda x: x%2, range(10))))
print(any(x>3 for x in [1,2,3]), all(x>0 for x in [1,2,3]))
