x = 10
x += 5; print(x)
x -= 3; print(x)
x *= 2; print(x)
x //= 4; print(x)
x **= 2; print(x)
x %= 7; print(x)
lst = [1, 2, 3]
lst += [4, 5]; print(lst)
lst *= 2; print(lst)
s = "ab"
s += "cd"; print(s)
s *= 2; print(s)
d = {"a": 1}
d |= {"b": 2}; print(d)
n = 5
n <<= 3; print(n)
n >>= 2; print(n)
n &= 6; print(n)
n |= 1; print(n)
n ^= 3; print(n)
big = 2**63
big += 1; print(big)
big *= big; print(big)
st = {1, 2, 3}
st &= {2, 3, 4}; print(sorted(st))
st |= {5}; print(sorted(st))
