from collections import Counter, deque, defaultdict, OrderedDict, ChainMap
c = Counter("abracadabra")
print(c.most_common(2))
print(sorted(c.elements()))
c.subtract("aaa")
print(c["a"])
print(sum(c.values()))
d = deque([1,2,3], maxlen=3)
d.append(4)
print(list(d))
d.appendleft(0)
print(list(d))
d.rotate(1)
print(list(d))
dd = defaultdict(list)
dd["x"].append(1)
dd["x"].append(2)
print(dict(dd))
od = OrderedDict([("a",1),("b",2)])
od.move_to_end("a")
print(list(od.keys()))
cm = ChainMap({"a":1}, {"a":2,"b":3})
print(cm["a"], cm["b"])
print(Counter([1,1,2]) + Counter([1,3]))
