print("a", "b", "c", sep="-")
print("no newline", end="")
print()
print("x", "y", sep="", end="!\n")
print(1, 2, 3, sep=", ")
print(*[1, 2, 3])
print(*range(3), sep="|")
print("tab\there")
print("a", end=" ")
print("b")
print([1,2], {3:4}, (5,6))
print("unicode: éü")
print(f"{1}", f"{2}", sep="+")
print(True, False, None)
print(1.0, 2.5, -0.0)
print("multi\nline")
