print(b"Hello World".swapcase())
print(b"hello world".title())
print(b"HeLLo".casefold() if hasattr(b"", "casefold") else b"n/a")
print(b"abc123".isalnum(), b"   ".isspace(), b"ABC".isupper(), b"abc".islower())
print(b"Title Case".istitle())
print(b"123".isdigit())
print(b"hello".center(11, b"-"))
print(b"key=value".partition(b"="))
print(b"a=b=c".rpartition(b"="))
print(b"xxhelloxx".strip(b"x"))
print(b"__lead".lstrip(b"_"))
print(b"trail__".rstrip(b"_"))
print(b"a b c".split())
print(b"a,b,,c".split(b","))
print(b"one\ntwo\nthree".split(b"\n", 1))
print(b"Hello".startswith((b"He", b"Wo")))
print(b"file.txt".endswith((b".txt", b".py")))
print(b"aaa".find(b"a", 1))
print(bytearray(b"hello").pop())
print(b"abcABC".translate(bytes.maketrans(b"abc", b"xyz")))
