print(isinstance(5, int))
print(isinstance(5, (int, float)))
print(isinstance("x", (int, float)))
print(isinstance(True, int))
print(isinstance([], list))
print(type(5) is int)
print(type([]) == list)
print(issubclass(bool, int))
print(issubclass(int, object))
print(isinstance(5, object))
print(isinstance(3.14, (int, float, complex)))
print(type("").__name__)
print(type(42).__name__)
print(isinstance((), tuple))
print(isinstance({}, dict))
print(isinstance(set(), set))
print(callable(print), callable(5))
print(isinstance(lambda: 0, type(lambda: 0)))
print(hasattr([], "append"), hasattr([], "foo"))
print(isinstance(b"", bytes))
print(all(isinstance(x, int) for x in [1,2,3]))
