from array import array
a = array("i", [1, 2, 3, 4])
print(a[0], a[-1])
print(len(a))
a.append(5)
print(list(a))
a.extend([6, 7])
print(list(a))
print(a.count(3))
print(a.index(4))
a.reverse()
print(list(a))
print(sum(a))
b = array("d", [1.5, 2.5])
print(list(b))
print(array("i", [1,2,3]).tolist())
c = array("i", range(5))
print(list(c))
print(a.typecode)
print(a.itemsize)
a2 = array("i", [10, 20])
a2.insert(1, 15)
print(list(a2))
print(max(array("i", [3,1,2])))
print(a)
print(array("i", []))
print(array("d", [1.0, 2.0]))
print(a[1:3])
print(a.pop())
print(list(a))
print(array("i", [1,2,3]) == array("i", [1,2,3]))
