import re
print(re.findall(r"\d+", "a1b22c333"))
print(re.sub(r"\s+", "_", "a  b   c"))
m = re.match(r"(\w+)@(\w+)", "user@host")
print(m.group(1), m.group(2), m.groups())
print(re.split(r"[,;]", "a,b;c,d"))
print(bool(re.search(r"^\d+$", "12345")))
print(re.sub(r"(\w)(\w)", r"\2\1", "abcd"))
print([m.start() for m in re.finditer(r"a", "banana")])
p = re.compile(r"(?P<year>\d{4})-(?P<month>\d{2})")
m2 = p.match("2026-07")
print(m2.group("year"), m2.group("month"))
print(m2.groupdict())
print(re.findall(r"(\d)(\d)", "1234"))
print(re.subn(r"o", "0", "foo boo"))
print(re.escape("a.b*c"))
