print("aaa".replace("a", "b", 2))
print("".join([]))
print("x".join([]))
print("abc".ljust(2))
print("abcdef".rjust(3))
print("Hello".encode().decode())
print("test".rpartition("t"))
print("no-sep".partition("X"))
print("aXbXc".rsplit("X", 1))
print("  ".isspace(), "".isspace())
print("Hello World".swapcase())
print("café".upper())
print("ABC".isupper(), "Abc".isupper())
print("hello world".rindex("o"))
print("mississippi".replace("iss", "XX"))
print(" ".join("abc"))
print("a\tb\tc".expandtabs(4))
print("Hello".format())
print("{{}}".format())
print("test".zfill(6))
print("-42".zfill(6))
