print("abc" * 3)
print("-".join(["a", "b", "c"]))
print("Hello World".split())
print("a\nb\nc".splitlines())
print("  x  ".strip(), "|", "xxyxx".strip("x"))
print("Hello".ljust(10, "."), "|")
print("Hello".zfill(10))
print("hello world".title())
print("HELLO".lower(), "world".upper())
print("hello".find("l"), "hello".rfind("l"))
print("hello".count("l"))
print("hello".index("e"))
print("abcdef"[::-1])
print("hello".startswith(("hi", "he")))
print("test.py".endswith((".py", ".txt")))
print("{:,.2f}".format(1234567.891))
print("café".encode("ascii", "replace"))
print(chr(0x1F600))
print("Hello, World".partition(", "))
