import re
print(re.sub(r"\d+", lambda m: str(int(m.group()) * 2), "a1b2c3"))
print(re.sub(r"(\w)(\w)", lambda m: m.group(2) + m.group(1), "abcd"))
m = re.match(r"(?P<key>\w+)=(?P<val>\w+)", "name=value")
print(m.groupdict())
print(re.findall(r"(\w)(\d)", "a1b2c3"))
print(re.match(r"\d+", "abc"))
print(re.sub(r"\s+", " ", "a   b    c"))
p = re.compile(r"\d+")
print(p.sub("X", "a1b22c333"))
print(re.escape("a.b*c"))
m2 = re.search(r"(\d+)-(\d+)", "range 10-20 end")
print(m2.group(0), m2.group(1), m2.group(2))
print(m2.span())
print(re.findall(r"[aeiou]", "hello world"))
