a = {1, 2, 3, 4}
b = {3, 4, 5, 6}
print(sorted(a & b))
print(sorted(a | b))
print(sorted(a - b))
print(sorted(a ^ b))
a.add(5)
print(sorted(a))
a.discard(1)
print(sorted(a))
a.remove(2)
print(sorted(a))
print(len({1, 1, 2, 2, 3}))
print({1, 2}.issubset({1, 2, 3}))
print({1, 2, 3}.issuperset({1, 2}))
print({1, 2}.isdisjoint({3, 4}))
c = {1, 2, 3}
c.update({4, 5})
print(sorted(c))
c.intersection_update({3, 4, 5, 6})
print(sorted(c))
print(sorted(frozenset([1, 2]) | {2, 3}))
print(set() == set())
print(sorted({x for x in range(5)} | {x for x in range(3, 8)}))
