print(str(42))
print(str(3.14))
print(str(True))
print(str(None))
print(str([1, 2, 3]))
print(str((1, 2)))
print(str({"a": 1}))
print(str({1, 2, 3}))
print(repr("hello"))
print(repr('with "quotes"'))
print(repr("with 'apostrophe'"))
print(repr(b"bytes"))
print(str(b"bytes"))
print(ascii("café"))
print(bin(255), oct(64), hex(255))
print(int("42"), float("3.14"), complex("1+2j"))
print(bool(1), bool(0), bool(""), bool("x"))
print(list("abc"), tuple([1, 2]), set([1, 1, 2]))
