print("aXbXc".rsplit("X", 1))
print("  hi  ".strip())
print("Hello".casefold())
print("a-b-c".split("-", 1))
print("{}{}".format(1, 2))
print("café".encode("utf-8").decode("utf-8"))
print("abcdef"[::-1])
print("ABC".swapcase())
print("hello world".replace("o", "0"))
print("x".rjust(5, "-"))
print("test".removeprefix("te"))
print(",".join(str(i) for i in range(3)))
