table = str.maketrans("aeiou", "AEIOU")
print("hello world".translate(table))
del_table = str.maketrans("", "", "aeiou")
print("hello world".translate(del_table))
mixed = str.maketrans({"a": "X", "e": None, "l": "LL"})
print("apple".translate(mixed))
print("abc123".translate(str.maketrans("123", "!@#")))
rot13 = str.maketrans("abcdefghijklmnopqrstuvwxyz", "nopqrstuvwxyzabcdefghijklm")
print("hello".translate(rot13))
