t = str.maketrans("abc", "xyz")
print("cab".translate(t))
t2 = str.maketrans({"a": "1", "b": None})
print("abcabc".translate(t2))
print("hello world".partition(" "))
print("a.b.c".rpartition("."))
print("line1\nline2\nline3".splitlines())
print("  x  ".center(9, "*"))
print("-42".zfill(6))
print("+42".zfill(6))
print("abcABC".swapcase())
print("hello".removeprefix("he"))
print("hello".removesuffix("lo"))
