print("Hello World".split())
print("a.b.c.d".rsplit(".", 2))
print("  trim  ".strip(), "|")
print("xxhelloxx".strip("x"))
print("Hello".startswith(("Hi", "He")))
print("test.py".endswith((".py", ".txt")))
print("a-b-c".count("-"))
print("hello".find("l"), "hello".rfind("l"))
print("Hello World".title())
print("hello world".capitalize())
print("HELLO".isupper(), "hello".islower(), "Hello123".isalnum())
print("   ".isspace(), "abc".isalpha(), "123".isdigit())
print("a\tb\tc".split("\t"))
print("hello".center(11, "-"))
print("%s has %d items" % ("list", 5))
print("{:,.2f}".format(1234567.891))
