print("abc".isalpha(), "ab1".isalpha())
print("123".isdigit(), "12.3".isdigit())
print("abc123".isalnum(), "abc!".isalnum())
print("   ".isspace(), "a b".isspace())
print("Hello".istitle(), "hello".istitle())
print("ABC".isupper(), "Abc".isupper())
print("abc".islower(), "Abc".islower())
print("var_1".isidentifier(), "1var".isidentifier())
print("hello world".title())
print("HELLO".casefold())
print("a\tb".expandtabs(4))
print("²".isdigit(), "½".isnumeric())
print("²".isdecimal(), "²".isdigit(), "²".isnumeric())
print("½".isdecimal(), "½".isdigit(), "½".isnumeric())
print("5".isdecimal(), "5".isdigit(), "5".isnumeric())
print("Ⅷ".isdecimal(), "Ⅷ".isdigit(), "Ⅷ".isnumeric())
print("٥".isdecimal(), "٥".isdigit(), "٥".isnumeric())
print("①".isdigit(), "①".isnumeric())
