print("a,b,c".partition(","))
print("hello world".title())
print("  x  ".center(9, "*"))
print("abc".translate(str.maketrans("abc", "xyz")))
print("a\tb".expandtabs(4))
print("line1\nline2".splitlines())
print("{name} is {age}".format_map({"name": "X", "age": 5}))
print("%d and %s" % (42, "hi"))
print("{:,}".format(1234567))
print("{:+.2f}".format(3.14159))
print("{:>10}".format("hi"))
