print("HELLO world".title())
print("hello".ljust(8) + "|")
print("hello".rjust(8) + "|")
print("hello".zfill(8))
print("-42".zfill(6))
print("aXbXc".split("X"))
print("a b  c   d".split())
print("  strip  ".strip())
print("Hello".startswith(("Hi", "He")))
print("test.py".endswith((".py", ".txt")))
print("aaa".count("a"))
print("abcabc".replace("bc", "XY"))
print("MixedCASE".lower())
print("café".casefold() == "café".casefold())
print("a\tb\tc".split("\t"))
print("hello world foo".rsplit(" ", 1))
print(" ".join(["a", "b", "c"]))
print("Hello, World".find(","))
print("no comma".find(","))
