print("hello world".title())
print("__init__".strip("_"))
print("a.b.c.d".split(".", 2))
print("  ".isspace())
print("".isspace())
print("Hello".encode("utf-16").decode("utf-16"))
print("abcABC123".swapcase())
print(",".join(str(i) for i in range(5)))
print("x" * 0)
print("abc"[::2])
print("hello".partition("ll"))
print("hello".rpartition("l"))
print("test\ttab".expandtabs(4))
print(f"{'left':<10}{'right':>10}")
print("Hello World".casefold())
print("résumé".upper())
print(len("👍"))
