print("abc".isalpha(), "ab1".isalpha())
print("123".isdigit(), "12a".isdigit())
print("abc123".isalnum(), "abc!".isalnum())
print("   ".isspace(), "".isspace())
print("HELLO".isupper(), "Hello".isupper())
print("hello".islower(), "Hello".islower())
print("Hello World".istitle())
print("var_name".isidentifier(), "123var".isidentifier())
print("hello".isprintable(), "he\tllo".isprintable())
print("123".isdecimal(), "½".isdecimal())
print("½".isnumeric(), "abc".isnumeric())
print("".isalpha())
print("a".isascii(), "café".isascii())
print("Title Case".istitle())
print("ALLCAPS".isupper())
print("mixedCASE".islower())
print("42".isdigit())
print("3.14".isdigit())
