print("a,b,c,d".split(","))
print("a,b,c,d".split(",", 2))
print("a b c".split())
print("".split(","))
print("abc".split(""))  if False else print("skip empty sep")
print("  multiple   spaces  ".split())
print("one".split(","))
print("a\nb\nc".splitlines())
print("x-y-z".rsplit("-", 1))
print("|".join(["a", "b", "c"]))
print("".join(["x", "y", "z"]))
print(", ".join(str(i) for i in range(4)))
print("path/to/file".split("/"))
print("a=1;b=2;c=3".split(";"))
print("trailing,".split(","))
print(",leading".split(","))
print("a..b".split("."))
