print("a\nb\nc".splitlines(keepends=True))
print("hello".format())
print("{name} is {age}".format(name="Bob", age=30))
print("{0} {1} {0}".format("a", "b"))
print("{:>{width}}".format("hi", width=10))
print("value: {x[0]}".format(x=[1, 2, 3]))
print("{0.imag}".format(3+4j))
print("café".encode().decode())
print("  tab\there  ".strip())
print("Hello World Foo".split(" ", 1))
print("a-b-c-d".rsplit("-", 2))
print("".join([]))
print(":".join("abc"))
print("%s=%r" % ("key", "value"))
print("{:,}".format(1234567))
