print("Hello World".split(" "))
print("Hello World".rsplit(" "))
print("aaa".removeprefix("a"))
print("banana".removesuffix("na"))
print("Hello".ljust(10, "."))
print("café résumé".title())
print("  \t\n  ".strip())
print("123abc456".strip("0123456789"))
print("MixedCase123".isalnum())
print("hello world".index("world"))
print("abcdef"[::2])
print("HELLO".lower().capitalize())
print("a-b-c".replace("-", "_"))
print("  x  ".strip() + "|")
print("test".center(10))
print("padding".rjust(15, "*"))
print("one two three".count(" "))
print("Hello\nWorld".split("\n"))
print(len("héllo wörld"))
