print("hello world".title())
print("HELLO".capitalize())
print("MixedCase".swapcase())
print("  spaces  ".strip())
print("aaa".replace("a", "b", 2))
print("a,b,c".split(","))
print("-".join(["x", "y", "z"]))
print("hello".ljust(10, "."))
print("hello".rjust(10, "."))
print("hello".center(11, "-"))
print("café".upper())
print("STRASSE".lower())
print("Hello World".count("o"))
print("abcabc".find("c", 3))
print("abcabc".rfind("a"))
