print("Hello World".upper())
print("Hello World".lower())
print("hello world".title())
print("Hello World".swapcase())
print("hello".capitalize())
print("HELLO".casefold())
print("ß".upper())
print("İ".lower())
print("hello world".title().swapcase())
print("  Multiple   Words  Here  ".title())
print("abc123def".upper())
print("Test-Case_Name".title())
print("it's a test".title())
print("2nd place".title())
print("HELLO".isupper(), "hello".islower())
print("Hello".istitle(), "HELLO".istitle())
