t = (1, 2, 3, 4, 5)
print(t[0], t[-1])
print(t[1:3])
print(t[::2])
print(t[::-1])
print(len(t))
print(t + (6, 7))
print(t * 2)
print(3 in t, 10 in t)
print(t.count(3), t.index(4))
print(max(t), min(t), sum(t))
print(sorted(t, reverse=True))
a, b, *rest = t
print(a, b, rest)
print(tuple(range(5)))
print(tuple("abc"))
nested = ((1, 2), (3, 4))
print(nested[0][1])
x, (y, z) = 1, (2, 3)
print(x, y, z)
print((1,) + (2,) + (3,))
single = (42,)
print(single, len(single))
empty = ()
print(empty, len(empty))
