gens = list(lambda: k for k in range(3))
print([g() for g in gens])
print([f() for f in (lambda: k for k in range(3))])
print([f() for f in (lambda: k * 10 for k in range(4))])
print([f(100) for f in (lambda x: x + i for i in range(3))])
print([f() for f in (lambda: k for k in range(3) if k % 2 == 0)])
print(sum(x for x in range(5)))
print(list(x*2 for x in range(4)))
print(max(x for x in [3, 1, 4, 1, 5]))
g = (x**2 for x in range(5))
print(next(g), next(g))
print(list(g))
print(sorted(len(w) for w in "a bb ccc".split()))
