b = b"Hello, World"
print(b.upper(), b.lower())
print(b.split(b", "))
print(b.replace(b"o", b"0"))
print(b.startswith(b"Hello"), b.endswith(b"World"))
print(b.find(b"World"), b.index(b","))
print(b.count(b"l"))
print(b[:5], b[7:], b[::-1])
print(len(b))
print(b + b"!")
print(b * 2)
print(bytes([104, 105]))
print(b"abc".hex())
print(bytes.fromhex("68656c6c6f"))
print(b"HELLO".isupper(), b"hello".islower())
print(b"  trim  ".strip())
print(b"a\tb\tc".split(b"\t"))
print(b"x".join([b"1", b"2", b"3"]))
print(b"Hello".ljust(10, b"."), b"Hi".rjust(5, b"*"))
print(b"Hello".center(11, b"-"))
print(list(b"ABC"))
print(bytes(range(65, 70)))
print(b"aAbBcC".swapcase())
print(b"hello world".title())
print(b"HELLO".capitalize())
ba = bytearray(b"hello")
ba[0] = ord("H")
print(ba)
ba.append(33)
print(ba)
ba.extend(b" world")
print(ba)
ba.insert(0, ord(">"))
print(ba)
print(ba.pop())
print(ba)
ba.reverse()
print(ba)
print(bytes(ba))
print(b"test".translate(bytes.maketrans(b"te", b"TE")))
print(b"aaa".replace(b"a", b"bb"))
print(int.from_bytes(b"\x01\x02", "big"), int.from_bytes(b"\x01\x02", "little"))
print((513).to_bytes(2, "big"), (513).to_bytes(2, "little"))
print(b"hello"[1], b"hello"[-1])
print(b"cafe".decode())
print(bytes(5))
print(b"a" in b"abc", b"x" in b"abc")
print(b"ABCDEF".hex(":"))
print(b"ABCDEF".hex(" ", 2))
print(bytearray([1, 2, 3]) == bytearray([1, 2, 3]))
print(b"hello".removeprefix(b"he"), b"hello".removesuffix(b"lo"))
print(b"a,b,c".rsplit(b",", 1))
print(b"Hello World".rfind(b"o"))
