print("café".encode("utf-8"))
print("café".encode("latin-1"))
print("hello".encode("ascii"))
print(b"caf\xc3\xa9".decode("utf-8"))
print(b"caf\xe9".decode("latin-1"))
print("abc".encode("utf-16"))
print("A".encode("utf-32"))
print(b"\xff\xfe".decode("utf-16"))
print("日本".encode("utf-8").decode("utf-8"))
try:
    b"\xff".decode("utf-8")
except UnicodeDecodeError as e:
    print("decode err:", type(e).__name__)
try:
    "café".encode("ascii")
except UnicodeEncodeError as e:
    print("encode err:", type(e).__name__)
print("café".encode("ascii", "ignore"))
print("café".encode("ascii", "replace"))
print(b"\xff".decode("utf-8", "replace"))
print(b"\xff".decode("utf-8", "ignore"))
print("hello".encode().hex())
print(bytes.fromhex("48656c6c6f").decode())
print("100".encode("ascii"))
print(b"ABC".decode("ascii"))
print(len("café".encode("utf-8")), len("café"))
print("😀".encode("utf-8"), len("😀".encode("utf-8")))
print(bytearray("test", "utf-8"))
print("café".encode("utf-8", "strict"))
