mv = memoryview(b"abc")
print(mv.nbytes, mv.format, mv.itemsize, mv.ndim)
print(mv.shape, mv.strides, mv.suboffsets)
print(mv.readonly, mv.contiguous, mv.c_contiguous, mv.f_contiguous)
mb = memoryview(bytearray(b"xy"))
print(mb.nbytes, mb.readonly, mb.shape)
print(bytes(mv.obj), bytes(mb.obj))
print(memoryview(b"").nbytes, memoryview(b"").shape)
print(hasattr(mv, "nbytes"), hasattr(mv, "tobytes"), hasattr(mv, "missing"))
print(mv.tobytes(), mv.tolist())
