mv = memoryview(b"abcdef")
print(type(mv).__name__)
print(bytes(mv))
print(len(mv))
print(mv[0], mv[1])
print(mv.tobytes(), mv.hex())
print(mv.tolist())
print(list(mv))
print(bytes(memoryview(b"hi")))
ba = bytearray(b"xyz")
mv2 = memoryview(ba)
print(mv2.tobytes())
ba[0] = ord("Q")
print(mv2.tobytes())               # view reflects the mutation
print(memoryview(b"abc") == b"abc")
print(bytes(mv[1:4]))
