from collections import deque, Counter, OrderedDict, defaultdict, ChainMap, namedtuple
d = deque([1, 2, 3, 4, 5])
d.rotate(2); print(list(d))
d.rotate(-3); print(list(d))
print(d.index(3), d.count(2))
d.insert(0, 99); print(list(d))
d.remove(99); print(list(d))
dm = deque(maxlen=3)
for i in range(5): dm.append(i)
print(list(dm))
dm.appendleft(-1); print(list(dm))
c = Counter("abracadabra")
print(c.most_common(2))
print(sorted(c.elements()) == sorted("abracadabra"))
c.subtract("abc"); print(dict(c))
print((Counter(a=3, b=1) & Counter(a=1, b=2)))
print((Counter(a=3) | Counter(a=1, b=5)))
print(Counter([1,2,2,3]).total() if hasattr(Counter(), "total") else "no-total")
od = OrderedDict([("a", 1), ("b", 2), ("c", 3)])
od.move_to_end("a"); print(list(od))
od.move_to_end("c", last=False); print(list(od))
print(od.popitem(last=False))
dd = defaultdict(lambda: defaultdict(int))
dd["x"]["y"] += 1; print(dict(dd["x"]))
cm = ChainMap({"a": 1}, {"a": 2, "b": 3})
print(cm["a"], cm["b"], list(cm.keys()))
child = cm.new_child({"c": 4})
print(child["c"], child["a"])
print(len(cm.maps))
Pt = namedtuple("Pt", ["x", "y", "z"], defaults=[0, 0])
p = Pt(1)
print(p, p._asdict(), p._replace(y=5))
print(Pt._fields, Pt._field_defaults)
print(Pt._make([1, 2, 3]))
