import hashlib
print(hashlib.md5(b"hello").hexdigest())
print(hashlib.sha1(b"hello").hexdigest())
print(hashlib.sha256(b"hello").hexdigest())
print(hashlib.sha512(b"hello").hexdigest()[:32])
print(hashlib.sha224(b"test").hexdigest())
print(hashlib.sha384(b"x").hexdigest()[:20])
h = hashlib.sha256()
h.update(b"hello")
h.update(b" world")
print(h.hexdigest())
print(hashlib.sha256(b"hello world").hexdigest())
print(hashlib.md5(b"").hexdigest())
print(len(hashlib.sha256(b"x").digest()))
print(hashlib.sha256(b"abc").digest()[:4])
m = hashlib.md5(); m.update(b"a"); m.update(b"b")
print(m.hexdigest() == hashlib.md5(b"ab").hexdigest())
print(hashlib.new("sha256", b"data").hexdigest()[:16])
