from decimal import Decimal, getcontext, ROUND_HALF_UP, ROUND_DOWN
print(Decimal("0.1") + Decimal("0.2"))
print(Decimal("0.1") + Decimal("0.2") == Decimal("0.3"))
print(Decimal("10") / Decimal("3"))
print(Decimal("1.5").quantize(Decimal("1")))
print(Decimal("2.675").quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))
print(Decimal("100") * Decimal("1.08"))
print(Decimal("10") % Decimal("3"))
print(Decimal("2") ** 10)
print(Decimal("3.14159").quantize(Decimal("0.01")))
print(float(Decimal("3.14")))
print(int(Decimal("7.9")))
print(Decimal(10).sqrt())
print(Decimal("-5").copy_abs())
print(Decimal("1.23456789").quantize(Decimal("0.0001"), rounding=ROUND_DOWN))
print(sum([Decimal("0.1")] * 10))
print(Decimal("1") / Decimal("7"))
from fractions import Fraction
print(Fraction(1, 3) + Fraction(1, 6))
print(Fraction(3, 4) * Fraction(2, 3))
print(Fraction(1, 2) / Fraction(1, 4))
print(Fraction(6, 8))
print(Fraction("3/7"))
print(Fraction(0.5))
print(Fraction(1, 3) < Fraction(1, 2))
print(Fraction(10, 4).numerator, Fraction(10, 4).denominator)
print(float(Fraction(1, 3)))
print(Fraction(1, 2) + Fraction(1, 3) + Fraction(1, 6))
print(Fraction(22, 7).limit_denominator(10))
print(Fraction(2, 4) == Fraction(1, 2))
print(Fraction(5) + 3)
print(Fraction(1, 2) ** 2)
print(sum([Fraction(1, 3)] * 3))
print(Fraction(7, 3).__floor__(), Fraction(7, 3).__ceil__())
print(abs(Fraction(-3, 4)))
mixed = Decimal("1.5") + Decimal(2)
print(mixed)
print(Decimal("1E3"))
print(Decimal("1.00").normalize())
