import random
random.seed(42)
print(random.random())
print(random.random())
random.seed(42)
print(random.getrandbits(32))
random.seed(42)
print(random.getrandbits(10))
random.seed(42)
print(random.getrandbits(100))
random.seed(42)
print([random.randint(1, 100) for _ in range(5)])
random.seed(42)
print([random.randrange(0, 50, 3) for _ in range(5)])
random.seed(1)
print([random.choice("ABCDE") for _ in range(5)])
random.seed(1)
l = list(range(10)); random.shuffle(l); print(l)
random.seed(1)
print(random.sample(range(100), 5))
random.seed(7)
print(random.uniform(1, 2))
random.seed(0)
print(random.random())
random.seed(123456789)
print(random.random())
