from collections import Counter, deque, defaultdict, OrderedDict, ChainMap, namedtuple
c = Counter("abracadabra")
print(c.most_common(2))
print(c["a"], c["z"])
c2 = Counter([1, 1, 2, 3, 3, 3])
print(dict(c2))
print(c2 + Counter([1, 2]))
print(c2 - Counter([1, 3]))
print(c2 & Counter([1, 1, 3]))
print(c2 | Counter([2, 2]))
print(sum(c2.values()))
c3 = Counter(a=3, b=1)
c3.update(a=1, c=2)
print(dict(c3))
print(list(c.elements())[:3])
d = deque([1, 2, 3])
d.append(4)
d.appendleft(0)
print(list(d))
d.rotate(2)
print(list(d))
d.rotate(-1)
print(list(d))
dm = deque([1, 2, 3], maxlen=3)
dm.append(4)
print(list(dm))
d.extend([5, 6])
d.extendleft([9])
print(list(d))
print(d.pop(), d.popleft())
dd = defaultdict(list)
dd["a"].append(1)
dd["a"].append(2)
dd["b"].append(3)
print(dict(dd))
dd2 = defaultdict(int)
for c in "hello":
    dd2[c] += 1
print(dict(dd2))
od = OrderedDict()
od["c"] = 3
od["a"] = 1
od["b"] = 2
print(list(od.keys()))
od.move_to_end("c")
print(list(od.keys()))
cm = ChainMap({"a": 1}, {"b": 2}, {"a": 3})
print(cm["a"], cm["b"])
print(dict(cm))
Point = namedtuple("Point", ["x", "y"])
p = Point(1, 2)
print(p.x, p.y, p[0], p[1])
print(p._asdict())
print(p._replace(x=10))
Point3D = namedtuple("Point3D", "x y z")
print(Point3D(1, 2, 3))
print(c.total())
