from collections import deque
dq = deque([1, 2, 3, 4, 5])
print(dq.index(3))
print(dq.count(2))
dq.insert(2, 99)
print(list(dq))
dq.remove(99)
print(list(dq))
dq.reverse()
print(list(dq))
print(3 in dq, 99 in dq)
dq2 = deque("abc")
print(list(dq2))
print(dq2[0], dq2[-1])
dq3 = deque([1, 2, 3], maxlen=5)
print(dq3.maxlen)
dq3.rotate(1)
print(list(dq3))
dq3.rotate(-2)
print(list(dq3))
d = {"a": 1, "b": 2, "c": 3}
keys = d.keys()
values = d.values()
items = d.items()
print(list(keys), list(values))
print("a" in keys, 1 in values)
print(len(keys), len(items))
print(sorted(keys), sorted(values))
d["d"] = 4
print(len(keys))
print(list(items))
print(("a", 1) in items)
k1 = {"a": 1, "b": 2}.keys()
k2 = {"b": 2, "c": 3}.keys()
print(sorted(k1 | k2))
print(sorted(k1 & k2))
print(sorted(k1 - k2))
print(sorted(k1 ^ k2))
dv = {1: "a", 2: "b", 3: "c"}
print(max(dv.keys()), min(dv.keys()))
print(sum(dv.keys()))
for k, v in dv.items():
    pass
print(list(reversed(list(dv.keys()))))
print([k for k in dv])
print({k: v for k, v in dv.items()})
counts = {"x": 5, "y": 3, "z": 8}
print(max(counts, key=counts.get))
print(sorted(counts, key=counts.get))
print(sorted(counts.items(), key=lambda x: x[1]))
mapping = dict(zip("abc", [3, 1, 2]))
print(sorted(mapping.items(), key=lambda kv: kv[1]))
dq4 = deque(range(5))
dq4.extendleft([10, 20])
print(list(dq4))
dq5 = deque([1, 2, 3])
dq5.appendleft(0)
dq5.append(4)
print(list(dq5))
print(dq5.popleft(), dq5.pop())
print(list(dq5))
