print(f"{float('nan'):f}", f"{float('inf'):f}", f"{float('-inf'):f}")
print(f"{float('nan'):+f}", f"{float('inf'):+f}")
print(f"{float('nan'):F}", f"{float('inf'):F}")
print(f"{float('inf'):e}", f"{float('nan'):g}")
print(f"{float('inf'):E}", f"{float('nan'):G}")
print("{:.2f}".format(float('nan')))
print(format(float('inf'), 'f'), format(float('-inf'), 'f'))
print(f"{float('nan'):>10f}|")
print(f"{float('inf'):%}")
print(str(float('nan')), str(float('inf')), repr(float('nan')))
