print("{} {}".format("a", "b"))
print("{0} {1} {0}".format("x", "y"))
print("{name} is {age}".format(name="Bob", age=30))
print("{0[0]} {0[1]}".format([10, 20]))
print("{0[key]}".format({"key": "value"}))
print("{:>10}".format("right"))
print("{:<10}|".format("left"))
print("{:^10}|".format("center"))
print("{:*^20}".format("padded"))
print("{:.2f}".format(3.14159))
print("{:,}".format(1000000))
print("{:+.2f}".format(3.14))
print("{:x}".format(255))
print("{:#x}".format(255))
print("{:08b}".format(5))
print("{:.2%}".format(0.1234))
print("{:e}".format(123456.789))
print("{:>{width}}".format("hi", width=10))
print("{:.{prec}f}".format(3.14159, prec=3))
print("{0.real} {0.imag}".format(3 + 4j))
class Obj:
    def __init__(self):
        self.name = "test"
        self.value = 42
o = Obj()
print("{0.name} = {0.value}".format(o))
print("{obj.name}".format(obj=o))
data = {"user": {"name": "Alice", "id": 1}}
print("{0[user][name]}".format(data))
print("Result: {result:>8}".format(result="OK"))
print("{:d}".format(42))
print("{:5d}".format(42))
print("{:<5d}|".format(42))
print("{:=+8.2f}".format(3.14))
matrix = [[1, 2], [3, 4]]
print("{0[0][0]} {0[1][1]}".format(matrix))
print("{:_>10}".format("x"))
print("{:.3g}".format(0.00012345))
print("{{literal}}".format())
print("{0}{1}{0}".format("a", "b"))
print("Percentage: {:.1%}".format(0.856))
print("{:+d} {:+d}".format(5, -5))
print("{message}: {code}".format(message="Error", code=500))
print("{:>3}".format(7), "{:>3}".format(77), "{:>3}".format(777))
items = ["apple", "banana"]
print("{}, {}".format(*items))
kwargs = {"a": 1, "b": 2}
print("{a} {b}".format(**kwargs))
print("{:.0f}".format(2.5), "{:.0f}".format(3.5))
print("{name!r}".format(name="test"))
print("{0!s} {0!r}".format("hi"))
