print("{} {} {}".format(1, 2, 3), "{2} {1} {0}".format("a", "b", "c"))
print("{name} is {age}".format(name="X", age=5))
print("{:>10}".format("hi"), "{:^10}".format("hi"), "{:<10}".format("hi"))
print("{:.2f}".format(3.14159), "{:+d}".format(5), "{:,}".format(1000000))
print("Hello".upper(), "WORLD".lower(), "hello world".title())
print("  trim  ".strip(), "aaXbb".replace("a", ""), "a,b,c".split(","))
print("-".join(["1", "2", "3"]), "abc".find("b"), "abcabc".rfind("a"))
print("hello".startswith("he"), "hello".endswith("lo"), "abc" in "xabcy")
print("Hello World".count("o"), "aAbBcC".swapcase())
print("café".encode("utf-8"), b"caf\xc3\xa9".decode("utf-8"))
print("%s and %d" % ("text", 42), "%.3f" % 3.14159)
print(f"{3.14:.1f}", f"{42:05d}", f"{255:x}", f"{'hi':>5}")
print("test".ljust(8, ".") + "|", "test".rjust(8, "."), "5".zfill(3))
