print("Hello World".casefold(), "STRASSE".casefold())
print("{name} is {age}".format_map({"name": "Bob", "age": 30}))
print("a-b-c".split("-"), "a-b-c".rsplit("-", 1))
print("hello".translate(str.maketrans("el", "ip")))
print("  hi  ".strip(), "xxhixx".strip("x"), "hello".removeprefix("he"))
print("Hello".encode("utf-16").decode("utf-16"))
print("aAbBcC".swapcase(), "hello world".title())
print("42".isdigit(), "abc".isalpha(), "abc123".isalnum(), "   ".isspace())
print("Hello".center(11, "-"), "5".rjust(3, "0"))
print("a,b,,c".split(","), "a b  c".split())
print("line1\nline2\nline3".splitlines())
print("%s=%d" % ("x", 5), "{0:,}".format(1000000))
print("café".encode("utf-8").hex(), bytes.fromhex("636166c3a9").decode("utf-8"))
print("hello world foo".partition(" "), "a.b.c.d".rpartition("."))
print("ABCDEF".isupper(), "abcdef".islower(), "Hello World".istitle())
print(len("héllo"), "héllo"[1], "héllo".upper())
print("test".ljust(8).rstrip(), "  test  ".lstrip())
print("aaa".replace("a", "bb"), "aaa".count("a"), "aaa".find("a", 1))
