s = "Hello, World, Foo"
print(s.partition(", "), s.rpartition(", "))
print(s.rsplit(", ", 1), s.split(", ", 1))
print("a\nb\r\nc\rd".splitlines(), "a\nb".splitlines(keepends=True))
print("hi".center(10, "*"), "42".zfill(5), "-42".zfill(5))
print("a\tb\tc".expandtabs(4), "x".ljust(5, "."), "x".rjust(5, "."))
print("Hello World".title(), "hello world".capitalize(), "MiXeD".swapcase())
print("  x  ".strip(), "xxax".strip("x"), "aXbXc".replace("X", "-", 1))
print("abcabc".removeprefix("abc"), "abcabc".removesuffix("abc"))
print("café".encode("utf-8"), b"caf\xc3\xa9".decode("utf-8"))
print("{0}-{1}-{0}".format("a", "b"), "{name}".format(name="x"))
print("%s and %d and %.2f" % ("txt", 5, 3.14159))
print("%(a)s %(b)d" % {"a": "hi", "b": 7})
print("{:>10.3f}".format(3.14159), "{:+.2e}".format(12345.678))
print("aXbXcXd".split("X", 2), "".join(["a", "b", "c"]))
print("Hello".startswith(("Hi", "He")), "World".endswith(("ld", "xy")))
