print("a\tb\nc".encode("unicode-escape"))
print("hello".encode("unicode-escape"))
print("café".encode("unicode-escape"))
print("back\\slash".encode("unicode-escape"))
print("tab\there".encode("unicode-escape"))
print("newline\r\n".encode("unicode-escape"))
print("😀".encode("unicode-escape"))
print("\x00\x01\x1f".encode("unicode-escape"))
print("mix é 中 😀".encode("unicode-escape"))
print("quote\"'apos".encode("unicode-escape"))
print("".encode("unicode-escape"))
print("normal ascii 123".encode("unicode-escape"))
print("unicode_escape alias".encode("unicode_escape"))
