print("ABC".encode("utf-32").hex())
print("ABC".encode("utf-32-le").hex())
print("ABC".encode("utf-32-be").hex())
print("café".encode("utf-32-le").hex())
raw = "hello".encode("utf-32")
print(raw.decode("utf-32"))
print(b"\x41\x00\x00\x00\x42\x00\x00\x00".decode("utf-32-le"))
print("日本".encode("utf-32-be").hex())
print("😀".encode("utf-32-le").hex())
print("roundtrip".encode("utf-32").decode("utf-32"))
