s = {3, 1, 2}
s.add(4)
print(sorted(s))
s.discard(2)
print(sorted(s))
s.remove(1)
print(sorted(s))
try:
    s.remove(99)
except KeyError:
    print("keyerror")
s.discard(99)
print("discard ok")
a = {1, 2, 3}
b = {2, 3, 4}
print(sorted(a.union(b)))
print(sorted(a.intersection(b)))
print(sorted(a.difference(b)))
print(sorted(a.symmetric_difference(b)))
c = a.copy()
c.add(10)
print(sorted(a), sorted(c))
print(a.union(b, {5, 6}) == {1, 2, 3, 4, 5, 6})
a.update({7, 8})
print(sorted(a))
a.intersection_update({7, 8, 9})
print(sorted(a))
a.difference_update({8})
print(sorted(a))
d = {1, 2, 3}
d.symmetric_difference_update({3, 4})
print(sorted(d))
print(len({1, 1, 2, 2, 3, 3}))
empty = set()
print(len(empty), bool(empty))
print(set() | {1, 2})
print({1, 2, 3} > {1, 2})
print({1, 2} < {1, 2, 3})
print({1, 2}.issubset({1, 2, 3}))
print({1, 2, 3}.issuperset({1}))
print({1, 2}.isdisjoint({3, 4}))
x = {1, 2, 3}
popped = x.pop()
print(popped in {1, 2, 3}, len(x))
x.clear()
print(len(x))
fs1 = frozenset([1, 2, 3])
fs2 = frozenset([2, 3, 4])
print(sorted(fs1 | fs2))
print(sorted(fs1 & fs2))
print(fs1.union(fs2) == frozenset([1, 2, 3, 4]))
nested = {frozenset([1, 2]), frozenset([3, 4])}
print(len(nested))
print(frozenset([1, 2]) in nested)
s2 = {x for x in range(10) if x % 2 == 0}
print(sorted(s2))
print(sorted({x * y for x in range(1, 3) for y in range(1, 3)}))
combined = {1, 2, 3} | {3, 4, 5} & {5, 6, 7}
print(sorted(combined))
print(len({i % 3 for i in range(100)}))
