def trap(fn):
    try:
        fn(); return "NO-ERROR"
    except Exception as e:
        return f"{type(e).__name__}: {e}"
print(trap(lambda: [1, 2, 3][10]))
print(trap(lambda: {"a": 1}["b"]))
print(trap(lambda: int("abc")))
print(trap(lambda: 1 / 0))
print(trap(lambda: [] + {}))
print(trap(lambda: "a" + 1))
print(trap(lambda: len(5)))
print(trap(lambda: [1, 2].index(5)))
print(trap(lambda: (1, 2).index(5)))
print(trap(lambda: "hello".index("z")))
print(trap(lambda: {1, 2}.remove(5)))
print(trap(lambda: [].pop()))
print(trap(lambda: {}.popitem()))
print(trap(lambda: next(iter([]))))
print(trap(lambda: 10 % 0))
print(trap(lambda: [1, 2, 3][1.5]))
print(trap(lambda: "abc"[10]))
print(trap(lambda: float("xyz")))
print(trap(lambda: [1, 2, 3].remove(9)))
print(trap(lambda: dict(1)))
print(trap(lambda: max([])))
print(trap(lambda: min([])))
print(trap(lambda: sum([1, "a"])))
print(trap(lambda: "{}".format()))
print(trap(lambda: "{0} {1}".format("only")))
print(trap(lambda: sorted([1, "a"])))
print(trap(lambda: abs("x")))
print(trap(lambda: ord("ab")))
print(trap(lambda: chr(-1)))
print(trap(lambda: bytes([256])))
print(trap(lambda: "x".encode("badcodec")))
print(trap(lambda: int("10", 40)))
print(trap(lambda: range(1, 2, 0)))
