print("a", "b", "c")
print("a", "b", "c", sep=", ")
print("a", "b", "c", sep="")
print("no newline", end="")
print(" continued")
print("x", "y", sep="-", end="!\n")
print()
print("tab", "sep", sep="\t")
print(1, 2, 3, sep=" | ")
print(*[1, 2, 3])
print(*[1, 2, 3], sep=", ")
print(*range(5))
import sys
print("to stdout", file=sys.stdout)
print("multiple", "values", "here", sep="_", end=".\n")
print("unicode:", "café", "→", "test")
values = [1, 2, 3]
print(f"list: {values}", "extra", sep=" >> ")
print("nested", ["a", ["b", "c"]], {"k": "v"})
print(True, False, None)
print(3.14, 2.71828)
print(-0.0, 0.0)
print(1e10, 1e-10)
print("newlines\nin\nstring")
print(r"raw\nstring")
print(b"bytes")
print("quote's", 'double"quote')
for i in range(3):
    print(i, end=" ")
print()
data = {"name": "test", "value": 42}
for k, v in data.items():
    print(f"{k}={v}", end="; ")
print()
print(", ".join(str(x) for x in range(5)))
print("|".join(["a", "b", "c"]))
import io
buf = io.StringIO()
print("captured", "output", file=buf, sep="-")
print(buf.getvalue().strip())
